version: '3.7'
services:
  mongodb-service:
    image: mongo:6.0
    container_name: ${DB_NAME}
    networks:
      - api-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - ${DB_PORT}:${DB_PORT}
    env_file: .env
    restart: always
    command: 'mongod --auth'

  mongo-express:
    image: mongo-express
    container_name: mongo-gui
    restart: always
    networks:
      - api-network
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USER}:${DB_PASSWORD}@mongodb-service:${DB_PORT}/
    env_file: .env
    depends_on:
      - mongodb-service

networks:
    api-network: